from django.contrib import admin
from django.urls import path, include
from home import views  
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path("", views.index, name='home'),
    path("patient", views.patient, name='patient'),
    path("indoor", views.indoor, name='indoor'),
    path("doctor", views.doctor, name='doctor'),
    path("hplist", views.hplist, name='hplist'),
    path("hpPage", views.hpPage, name='hpPage'),
    path("ipPage", views.ipPage, name='ipPage'),
    path("ReIndoorAdmission", views.ReIndoorAdmission, name='ReIndoorAdmission'),
    path("oplist", views.oplist, name='oplist'),
    path("doctor", views.doctor, name='doctor'),
    path("portal", views.portal, name='portal'),
    path("addmin", views.addmin, name='admin'),
    path("services", views.services, name='services'),
    path("about", views.about, name='about'),
    path("contact", views.contact, name='contact'),
    path("appointment", views.appointment, name='appointment'),
    path("login", views.loginPage, name="login"),
    path("dlogin", views.dlogin, name="dlogin"),
    path("hplogin", views.hplogin, name="hplogin"),
    path("adlogin", views.adlogin, name="adlogin"),
    path('logout/', views.logoutUser, name="logout"),
    path('signup', views.registerPage, name="register"),
    path('checkup', views.checkup, name="chekup"),
    path('hpsegment', views.hpsegment, name="hpsegment"),
    path('hppatient', views.hppatient, name="hppatient"),
    path('OutdoorDoctor', views.OutdoorDoctor, name="outdoor docto"),
    path('HomePatient', views.HomePatient, name="home patient"),
    path('IndoorAdmission/', views.IndoorAdmission, name="indoor admission"),
    # path('saveenquiry', views.saveEnquiry, name="indoor saveenquiry"),
    # path('savedata', views.saveData, name="indoor savedata"),
    # path('saveindoordata', views.saveindoorData, name="indoor savedata"),
    #  path('saveoutdoordata', views.saveoutdoorData, name="outdoor savedata"),
    path('result', views.result, name="outdoor savedata"),
    path('update_contact/<str:pk>/', views.updatecontact, name="update_contact"),
    path('delete_contact/<int:pk>/', views.deletecontact, name="delete_contact"),
    path('delete_appointment/<int:pk>/', views.delete_appointment, name="delete_appointment"),
    path('update_outdoor/<str:pk>/', views.updateoutdoorpatient, name="update_outdoor"),
    path('delete_outdoor/<int:pk>/', views.deleteoutdoorpatient, name="delete_outdoor"),
    path('update_indoor/<str:pk>/', views.updateindoorpatient, name="update_indoor"),
    path('discharge_patient/<int:pk>/', views.dischargepatient, name="discharge_patient"),
    path('delete_indoor/<int:pk>/', views.deleteindoorpatient, name="Delete_indoor"),
    path('update_hp/<str:pk>/', views.update_hp, name="update_hp"),
    path('delete_hp/<int:pk>/', views.delete_hp, name="delete_hp"),
    path('housePatient', views.housePatient, name=" housePatient"),
    path('dhousePatient', views.dhousePatient, name=" dhousePatient"),
    path('report/', views.report, name=" report"),
     path('ipreport/', views.ipreport, name=" ipreport"),
    path('addreport/<str:pk>/', views.addreport, name=" addreport"),
    path('addIpreport/<str:pk>/', views.addIpreport, name=" addIpreport"),
    path('indoorpatient', views.indoorpatient, name=" indoorpatient"),
    path('dindoorpatient', views.dindoorpatient, name=" dindoorpatient"),
    path('indoorad/', views.indoorad, name="indoorad"),
     path("dis_msg", views.dismsg, name="Discharge Message"),
    path("cmsg", views.cmsg, name=" Message"),
    path('amsg/<int:pk>/', views.amsg, name="Confirmatin Massege"),
    path('hpmsg/<int:pk>/', views.hpmsg, name="Confirmatin Massege"),
    path('onlmsg/<int:pk>/', views.onlmsg, name="Confirmatin Massege"),
    path('profile/<int:pk>/', views.profile, name="profile"),
    path('ipmsg/<int:pk>/', views.ipmsg, name="Confirmatin Massege"),
    path("onlmsg", views.onlmsg, name=" Message"),
    path("rconfirm", views.rconfirm, name=" rconfirm"),
    path("aconfirm/<str:pk>/", views.aconfirm, name=" aconfirm"),
    path("iconfirm/<str:pk>/", views.iconfirm, name=" iconfirm"),
    path("ehp", views.ehp, name=" ehp"),
    path("eip", views.eip, name=" eip"),
    path("Readmit", views.Readmit, name=" Readmit"),
    path("Online_appointment", views.Online_appointment, name=" Online appointment"),
    path("outdoorPatient", views.outdoorPatient, name=" outdoorPatient"),
    path("HpOnline_appointment", views.HpOnline_appointment, name=" Online HpOnline_appointment"),
    path("dOnline_appointment", views.dOnline_appointment, name=" dOnline_appointment"),
    path('HomePatientAppointment/<str:pk>/', views.HomePatientAppointment, name="HomePatientAppointment"),
    # path('edit/<str:pk>/', views.edit, name=" edit"),
    
    # path('edit/<int:id>', views.edit, name=" edit"),
    
    # path("student", views.student, name='student'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
